package golac

import (
	"strings"

	iconv "github.com/djimenez/iconv-go"
	jsoniter "github.com/json-iterator/go"
)

// Document contains a result of lac.
type Document []Sentence

// Sentence
type Sentence struct {
	Word []string `json:"word,omitempty"`
	Tag  []string `json:"tag,omitempty"`
}

// Decode parse a json output generated by PaddleHub LAC.
func Decode(input string) (Document, error) {
	// build a converter at first
	t, err := iconv.ConvertString(input, "gbk", "utf-8")
	if err != nil {
		return nil, err
	}
	t = strings.Replace(t, `'`, `"`, -1)

	d := Document{}
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	json.Unmarshal([]byte(t), &d)

	return d, nil
}
